name: Android Build Release

on:
  push:
    tags:
      - v*
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        add-job-summary-as-pr-comment: on-failure # Valid values are 'never' (default), 'always', and 'on-failure'
        build-scan-publish: false
        build-scan-terms-of-use-agree: "no"

    - name: Build App
      run: |
        chmod +x gradlew
        ./gradlew assembleDefaultFlavor
        ls -hal
        find . -name *.apk -type f 

    - name: Archive APK
      uses: actions/upload-artifact@v4
      with:
        name: Archive Quillpad APK
        path: app/build/outputs/apk/defaultFlavor/release/app-defaultFlavor-release.apk
    
    - name: Rename app to release java-version
      if: ${{ github.ref_type == 'tag' }}
      env: 
        VERSION: ${{ github.ref_name }}
      run: |
        echo version = ${VERSION:1}
        echo "APK_VERSION=${VERSION:1}" >> $GITHUB_ENV
        cp -v app/build/outputs/apk/defaultFlavor/release/app-defaultFlavor-release.apk quillpad-${VERSION:1}.apk

    - name: Do Release
      uses: softprops/action-gh-release@v2
      if: ${{ github.ref_type == 'tag' }}
      with:
        files: quillpad-${{env.APK_VERSION}}.apk
        draft: true
